ContainerRestaurant/ContainerRestaurant-Server

build.gradle, src/main/java/container/restaurant/server/config/WebMvcConfig.java, src/main/java/container/restaurant/server/config/auth/CustomOAuth2UserService.java, src/main/java/container/restaurant/server/config/auth/LoginUser.java, src/main/java/container/restaurant/server/config/auth/LoginUserArgumentResolver.java, src/main/java/container/restaurant/server/config/auth/SecurityConfig.java, src/main/java/container/restaurant/server/config/auth/dto/SessionUser.java, src/main/java/container/restaurant/server/domain/exception/ResourceNotFoundException.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/domain/user/UserRepository.java, src/main/java/container/restaurant/server/domain/user/UserService.java, src/main/java/container/restaurant/server/domain/user/validator/NicknameConstraint.java, src/main/java/container/restaurant/server/domain/user/validator/NicknameConstraintValidator.java, src/main/java/container/restaurant/server/exceptioin/FailedAuthorizationException.java, src/main/java/container/restaurant/server/web/ExceptionAdvice.java, src/main/java/container/restaurant/server/web/UserController.java, src/main/java/container/restaurant/server/web/dto/ErrorDto.java, src/main/java/container/restaurant/server/web/dto/user/NicknameExistsDto.java, src/main/java/container/restaurant/server/web/dto/user/UserInfoDto.java, src/main/java/container/restaurant/server/web/dto/user/UserUpdateDto.java, src/test/java/container/restaurant/server/domain/user/UserRepositoryTest.java, src/test/java/container/restaurant/server/domain/user/UserTest.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java, src/test/java/container/restaurant/server/web/UserControllerTest.java
- CRUD 기능중 C 부분은 OAuth 2.0 로그인 부분에서 구현했고, RUD 에 대해 구현
- REST Docs 스니펫 구현
=> 유저 도메인에 대한 CRUD 기능 및 닉네임 중복 체크 기능 추가

commit_imojii/README.md
커밋 단위 기준으로 사용할 이모지들을 명세해 보았습니다.
=> 커밋 단위 명세 추가

src/main/java/container/restaurant/server/domain/feed/Feed.java, src/main/java/container/restaurant/server/domain/feed/FeedRepository.java, src/main/java/container/restaurant/server/domain/feed/picture/Picture.java, src/main/java/container/restaurant/server/domain/feed/picture/PictureRepository.java, src/test/java/container/restaurant/server/domain/feed/FeedTest.java, src/test/java/container/restaurant/server/domain/feed/picture/PictureTest.java
피드에서 관계되는 엔티티가 많아서 우선 기본 템플릿만 구현했다.
=> 피드 도메인만 추가

src/docs/asciidoc/index.adoc, src/main/java/container/restaurant/server/config/LinkerConfig.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLike.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeRepository.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeService.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/domain/user/scrap/FeedScrap.java, src/main/java/container/restaurant/server/domain/user/scrap/FeedScrapRepository.java, src/main/java/container/restaurant/server/domain/user/scrap/FeedScrapService.java, src/main/java/container/restaurant/server/web/FeedLikeController.java, src/main/java/container/restaurant/server/web/UserScrapController.java, src/main/java/container/restaurant/server/web/linker/FeedLikeLinker.java, src/main/java/container/restaurant/server/web/linker/UserScrapLinker.java, src/test/java/container/restaurant/server/domain/feed/like/FeedLikeRepositoryTest.java, src/test/java/container/restaurant/server/domain/user/scrap/FeedScrapRepositoryTest.java, src/test/java/container/restaurant/server/web/AuthListControllerTest.java, src/test/java/container/restaurant/server/web/FeedLikeControllerTest.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java, src/test/java/container/restaurant/server/web/UserControllerTest.java, src/test/java/container/restaurant/server/web/UserScrapControllerTest.java, src/test/java/container/restaurant/server/web/base/BaseMvcControllerTest.java, src/test/java/container/restaurant/server/web/base/BaseUserAndFeedControllerTest.java, src/test/java/container/restaurant/server/web/base/BaseUserControllerTest.java
피드 신고하기에 앞서 형태가 비슷한 피드 좋아요, 피드 스크랩 관련 기능들을 구현
=> 피드-유저 관계 엔티티 구현 1

build.gradle, src/main/java/container/restaurant/server/domain/comment/Comment.java, src/main/java/container/restaurant/server/domain/comment/CommentRepository.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLike.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLikeRepository.java, src/main/java/container/restaurant/server/domain/feed/Feed.java, src/main/java/container/restaurant/server/domain/feed/container/Container.java, src/main/java/container/restaurant/server/domain/feed/container/ContainerRepository.java, src/main/java/container/restaurant/server/domain/feed/picture/Image.java, src/main/java/container/restaurant/server/domain/report/Report.java, src/main/java/container/restaurant/server/domain/report/ReportComment.java, src/main/java/container/restaurant/server/domain/report/ReportFeed.java, src/main/java/container/restaurant/server/domain/report/ReportRepository.java, src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantRepository.java, src/main/java/container/restaurant/server/domain/restaurant/menu/Menu.java, src/main/java/container/restaurant/server/domain/restaurant/menu/MenuRepository.java, src/main/java/container/restaurant/server/domain/user/bookmark/FavoriteRestaurant.java, src/main/java/container/restaurant/server/domain/user/bookmark/FavoriteRestaurantRepository.java, src/test/java/container/restaurant/server/domain/feed/like/FeedLikeRepositoryTest.java, src/test/java/container/restaurant/server/domain/user/scrap/ScrapFeedRepositoryTest.java, src/test/java/container/restaurant/server/web/FeedLikeControllerTest.java, src/test/java/container/restaurant/server/web/base/BaseUserAndFeedControllerTest.java
=> :label: 전체 도메인 명세 및 리포지 토리추가

src/main/java/container/restaurant/server/config/auth/SecurityConfig.java, src/main/java/container/restaurant/server/domain/feed/Feed.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/web/FeedController.java, src/main/java/container/restaurant/server/web/dto/feed/FeedInfoDto.java, src/main/java/container/restaurant/server/web/linker/FeedLinker.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java
=> 피드 CRUD 기능 구현

src/main/java/container/restaurant/server/domain/comment/CommentService.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeService.java, src/main/java/container/restaurant/server/domain/feed/picture/ImageService.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantService.java, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java, src/main/java/container/restaurant/server/domain/user/UserService.java, src/main/java/container/restaurant/server/domain/user/scrap/ScrapFeedService.java, src/main/java/container/restaurant/server/web/RestaurantController.java, src/main/java/container/restaurant/server/web/UserController.java, src/main/java/container/restaurant/server/web/linker/CommentLinker.java, src/main/java/container/restaurant/server/web/linker/RestaurantFavoriteLinker.java, src/main/java/container/restaurant/server/web/linker/ScrapFeedLinker.java, src/main/java/container/restaurant/server/web/linker/UserLinker.java
각 도메인의 Respository를 해당 도메인의 Service 에서만 참조하도록 수정
+ 일부 경고를 해결
=> :recycle: Repository & Service 의존관계 개선

build.gradle, src/main/java/container/restaurant/server/config/quartz/RecommendFeedUpdateJobConfig.java, src/main/java/container/restaurant/server/domain/base/BaseEntity.java, src/main/java/container/restaurant/server/domain/feed/Feed.java, src/main/java/container/restaurant/server/domain/feed/FeedRepository.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/feed/recommend/RecommendFeedQueue.java, src/main/java/container/restaurant/server/domain/feed/recommend/RecommendFeedService.java, src/main/java/container/restaurant/server/domain/feed/recommend/RecommendFeedUpdateJob.java, src/main/java/container/restaurant/server/web/FeedController.java, src/main/java/container/restaurant/server/web/linker/FeedLinker.java, src/test/java/container/restaurant/server/domain/feed/FeedRepositoryTest.java, src/test/java/container/restaurant/server/domain/feed/FeedTest.java, src/test/java/container/restaurant/server/domain/feed/recommend/RecommendFeedUpdateJobTest.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java
=> :sparkle: 추천 피드 기능 추가

src/main/java/container/restaurant/server/domain/feed/picture/ImageService.java, src/main/java/container/restaurant/server/utils/MultipartUtility.java, src/main/java/container/restaurant/server/web/ImageController.java, src/main/java/container/restaurant/server/web/linker/ImageLinker.java, src/main/resources/application.properties, src/test/resources/application.properties
Spring Router 형식 반환이 어려워
Redirect 형식으로 이미지 반환 구현
기존 구조 Linker 형식으로 변경
#22 프록시 연결 방식  <실패>
=> :sparkles: 이미지 불러오기 구현

src/main/java/container/restaurant/server/config/auth/SecurityConfig.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantRepository.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantService.java, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java, src/main/java/container/restaurant/server/web/RestaurantController.java, src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantInfoDto.java, src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantNearInfoDto.java
식당이 포함된 피드의 난이도의 평점,
식당이 포함된 피드 개수 추가
#6
=> 식당 난이도 평점, 피드 개수 추가

src/main/java/container/restaurant/server/config/auth/SecurityConfig.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantRepository.java, src/main/java/container/restaurant/server/domain/restaurant/RestaurantService.java, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java, src/main/java/container/restaurant/server/domain/statistics/StatisticsService.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/domain/user/UserRepository.java, src/main/java/container/restaurant/server/domain/user/UserService.java, src/main/java/container/restaurant/server/web/RestaurantController.java, src/main/java/container/restaurant/server/web/StatisticsController.java, src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantInfoDto.java, src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantNearInfoDto.java, src/main/java/container/restaurant/server/web/dto/statistics/StatisticsInfoDto.java, src/main/java/container/restaurant/server/web/dto/statistics/StatisticsUserDto.java, src/main/java/container/restaurant/server/web/linker/StatisticsLinker.java
최근 사용자 조회 기능 재구현
캐시 미사용 방식으로 변경
#45
=> 최근, 최다 사용자 조회 구현

src/main/java/container/restaurant/server/domain/feed/Feed.java, src/main/java/container/restaurant/server/domain/feed/FeedRepository.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/feed/container/Container.java, src/main/java/container/restaurant/server/domain/feed/container/ContainerService.java, src/main/java/container/restaurant/server/domain/feed/hit/FeedHitRepository.java, src/main/java/container/restaurant/server/domain/restaurant/Restaurant.java, src/main/java/container/restaurant/server/domain/restaurant/menu/Menu.java, src/main/java/container/restaurant/server/domain/restaurant/menu/MenuRepository.java, src/main/java/container/restaurant/server/domain/restaurant/menu/MenuService.java, src/main/java/container/restaurant/server/web/dto/feed/FeedDetailDto.java, src/main/java/container/restaurant/server/web/dto/feed/FeedInfoDto.java, src/main/java/container/restaurant/server/web/dto/feed/FeedMenuDto.java, src/test/java/container/restaurant/server/domain/BaseServiceTest.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java, src/test/java/container/restaurant/server/domain/feed/container/ContainerServiceTest.java, src/test/java/container/restaurant/server/domain/restaurant/menu/MenuServiceTest.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java, src/test/java/container/restaurant/server/web/dto/feed/FeedInfoDtoTest.java
=> ❇️ 메뉴 / 용기 기능 구현

src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/domain/user/level/UserLevelFeedCount.java, src/main/java/container/restaurant/server/domain/user/level/UserLevelFeedCountRepository.java, src/main/java/container/restaurant/server/domain/user/level/UserLevelFeedCountService.java, src/test/java/container/restaurant/server/domain/BaseServiceTest.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java, src/test/java/container/restaurant/server/domain/user/UserTest.java, src/test/java/container/restaurant/server/domain/user/level/UserLevelFeedCountServiceTest.java, src/test/java/container/restaurant/server/domain/user/level/UserLevelFeedCountTest.java, src/test/java/container/restaurant/server/web/base/BaseUserAndFeedControllerTest.java
- 피드 작성/삭제 시 마다 유저 레벨링 체크
- 하루 최대 3개의 피드만 카운트
- 매일 00:05, 만료된 레벨 피드 카운트를 제거
Closes #55
=> ❇️ 유저 레벨링 기능 구현

src/docs/asciidoc/index.adoc, src/main/java/container/restaurant/server/domain/home/banner/Banner.java, src/main/java/container/restaurant/server/domain/home/banner/BannerRepository.java, src/main/java/container/restaurant/server/domain/home/banner/BannerService.java, src/main/java/container/restaurant/server/domain/home/phrase/Phrase.java, src/main/java/container/restaurant/server/domain/home/phrase/PhraseRepository.java, src/main/java/container/restaurant/server/domain/home/phrase/PhraseService.java, src/main/java/container/restaurant/server/utils/RandomPicker.java, src/main/java/container/restaurant/server/web/IndexController.java, src/main/java/container/restaurant/server/web/dto/banner/BannerInfoDto.java, src/test/java/container/restaurant/server/utils/RandomPickerTest.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java
- 기본 값으로 1개의 문구를 가지고있다.
- 매일 DB를 참조해 문구들을 업데이트한다.
- 업데이트할 문구가 없다면 기존의 문구들을 유지한다.
- 요청시 마다 랜덤으로 문구를 반환한다.
=> ✨ 메인화면 문구 추가

src/docs/asciidoc/index.adoc, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java, src/main/java/container/restaurant/server/web/RestaurantController.java, src/main/java/container/restaurant/server/web/RestaurantFavoriteController.java, src/main/java/container/restaurant/server/web/UserController.java, src/main/java/container/restaurant/server/web/dto/statistics/StatisticsInfoDto.java, src/main/java/container/restaurant/server/web/linker/RestaurantFavoriteLinker.java, src/main/java/container/restaurant/server/web/linker/RestaurantLinker.java, src/test/java/container/restaurant/server/web/PushControllerTest.java, src/test/java/container/restaurant/server/web/RestaurantControllerTest.java, src/test/java/container/restaurant/server/web/RestaurantFavoriteControllerTest.java, src/test/java/container/restaurant/server/web/StatisticsControllerTest.java, src/test/java/container/restaurant/server/web/UserControllerTest.java
아래 도메인에 대한 Docs 구현
- 푸쉬 토큰
- 식당
- 식당 즐겨찾기
- 통계정보
구현 못한 사항
- 주위 식당 API 는 SQL 관련 문제로 구현 보류
기타 사항
- 식당 즐겨찾기 관련 로직 일부 개선
- 식당 컨트롤러 관련 로직 일부 개선
#89
=> 푸쉬 토큰, 식당/즐겨찾기, 통계정보 Docs 구현

src/main/java/container/restaurant/server/web/IndexController.java, src/main/java/container/restaurant/server/web/RestaurantController.java, src/main/java/container/restaurant/server/web/UserController.java, src/main/java/container/restaurant/server/web/linker/RestaurantLinker.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java
:sparkles: '/' 경로에 주위 식당 조회 링크 추가
:hammer: 주위 식당 링크를 templated 로 사용할 수 있도록 RestaurantLinker 수정
Closes #79
=> ✨  '/' 경로에 주위 식당 조회 링크 추가

src/main/java/container/restaurant/server/domain/user/ContainerLevel.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/web/dto/IndexDto.java, src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java, src/main/java/container/restaurant/server/web/dto/statistics/StatisticsUserDto.java, src/main/java/container/restaurant/server/web/dto/user/UserDto.java, src/test/java/container/restaurant/server/domain/user/UserTest.java, src/test/java/container/restaurant/server/web/CommentControllerTest.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java, src/test/java/container/restaurant/server/web/UserControllerTest.java
:white_check_mark: 테스트 깨짐 수정
:label: User.level:Integer -> User:containerLevel:ContainerLevel 로 변경
- Dto 객체에서는 levelTitle 로 적용
:label: ContainerLevel 상수 추가
Closes #114
=> 🏷️  User 레벨 속성 변경

src/main/java/container/restaurant/server/domain/comment/Comment.java, src/main/java/container/restaurant/server/domain/comment/CommentRepository.java, src/main/java/container/restaurant/server/domain/comment/CommentService.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLikeRepository.java, src/main/java/container/restaurant/server/web/CommentController.java, src/main/java/container/restaurant/server/web/dto/comment/CommentInfoDto.java, src/test/java/container/restaurant/server/domain/comment/CommentServiceTest.java, src/test/java/container/restaurant/server/domain/comment/like/CommentLikeRepositoryTest.java, src/test/java/container/restaurant/server/web/CommentControllerTest.java
=> 🐛 댓글 버그 수정

src/docs/asciidoc/index.adoc, src/main/java/container/restaurant/server/config/auth/LoginUserFilter.java, src/main/java/container/restaurant/server/constant/Header.java, src/main/java/container/restaurant/server/domain/contract/Contract.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/home/banner/Banner.java, src/main/java/container/restaurant/server/web/UserController.java, src/main/java/container/restaurant/server/web/dto/restaurant/RestaurantInfoDto.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java, src/test/java/container/restaurant/server/web/CommentControllerTest.java, src/test/java/container/restaurant/server/web/CommentLikeControllerTest.java, src/test/java/container/restaurant/server/web/ContractControllerTest.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java, src/test/java/container/restaurant/server/web/IndexControllerTest.java, src/test/java/container/restaurant/server/web/UserControllerTest.java
=> 🐛 Docs 관련 버그 및 누락 수정

src/main/java/container/restaurant/server/config/auth/dto/OAuthAttributes.java
=> 🐛  이메일이 동의 되지 않은 경우 NPE 발생 오류 해결

appspec.yml, scripts/test-deploy/start.sh, src/main/java/container/restaurant/server/web/ProfileController.java, src/main/resources/application-deploy.properties, src/main/resources/application-deploy1.properties, src/main/resources/application-deploy2.properties, src/main/resources/application.properties
=> 🚀 배포 변경 Test/deploy

src/main/java/container/restaurant/server/domain/feed/Category.java
=> 🩹  일식 -> 돈까스/회/일식 으로 변경

src/main/java/container/restaurant/server/domain/feed/FeedRepository.java, src/main/java/container/restaurant/server/web/FeedController.java, src/main/java/container/restaurant/server/web/dto/feed/FeedDetailDto.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java
=> 🐛 피드 쓰기 버그 수정

src/main/java/container/restaurant/server/domain/user/OAuth2Registration.java, src/test/java/container/restaurant/server/domain/user/OAuth2RegistrationTest.java
=> 🐛  이메일 null 처리 예외 처리

src/main/java/container/restaurant/server/domain/feed/Category.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java
=> :bug: 피드리스트 정렬 카테고리 ALL 추가

src/main/java/container/restaurant/server/domain/comment/CommentRepository.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeRepository.java, src/main/java/container/restaurant/server/domain/user/scrap/ScrapFeedRepository.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java
=> :bug: 피드 삭제 오류 수정

src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/user/scrap/ScrapFeedRepository.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java
=> :bug: 피드 삭제 스크랩 유저 카운트 반영

src/main/java/container/restaurant/server/domain/comment/CommentRepository.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLikeRepository.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java
=> :bug: 댓글/대댓글 좋아요 케이스 피드 삭제 수정

src/main/java/container/restaurant/server/domain/contract/ContractService.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteService.java, src/main/java/container/restaurant/server/domain/user/ContainerLevel.java, src/main/java/container/restaurant/server/domain/user/User.java, src/main/java/container/restaurant/server/domain/user/level/UserLevelFeedCountService.java, src/main/java/container/restaurant/server/web/FeedController.java, src/main/java/container/restaurant/server/web/dto/feed/FeedCreateResultDto.java, src/main/java/container/restaurant/server/web/dto/feed/LevelUpDto.java, src/test/java/container/restaurant/server/domain/user/UserTest.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java
- 피드 작성시 레벨업 정보 반환 필요
- 찜한 개수가 표시되지 않음
- 약관 개수가 지속적으로 쌓이는 현상
=> 간단한 버그 및 추가 사항

src/main/java/container/restaurant/server/domain/comment/CommentRepository.java, src/main/java/container/restaurant/server/domain/comment/CommentService.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLikeRepository.java, src/main/java/container/restaurant/server/domain/comment/like/CommentLikeService.java, src/main/java/container/restaurant/server/domain/feed/FeedRepository.java, src/main/java/container/restaurant/server/domain/feed/FeedService.java, src/main/java/container/restaurant/server/domain/feed/hit/FeedHitRepository.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeRepository.java, src/main/java/container/restaurant/server/domain/feed/like/FeedLikeService.java, src/main/java/container/restaurant/server/domain/report/ReportCommentRepository.java, src/main/java/container/restaurant/server/domain/report/ReportFeedRepository.java, src/main/java/container/restaurant/server/domain/report/ReportService.java, src/main/java/container/restaurant/server/domain/restaurant/favorite/RestaurantFavoriteRepository.java, src/main/java/container/restaurant/server/domain/user/UserService.java, src/main/java/container/restaurant/server/domain/user/level/UserLevelFeedCountRepository.java, src/main/java/container/restaurant/server/domain/user/scrap/ScrapFeedRepository.java, src/main/java/container/restaurant/server/domain/user/scrap/ScrapFeedService.java, src/main/java/container/restaurant/server/web/UserController.java, src/test/java/container/restaurant/server/domain/feed/FeedServiceTest.java
=> :bug: 사용자 탈퇴 오류 수정

src/main/java/container/restaurant/server/domain/restaurant/RestaurantRepository.java
=> :sparkles: 피드가 없는 식당 정보 삭제

src/main/java/container/restaurant/server/domain/restaurant/RestaurantRepository.java, src/main/java/container/restaurant/server/web/dto/feed/FeedDetailDto.java, src/test/java/container/restaurant/server/web/FeedControllerTest.java
=> :sparkles: 피드상세 API 에서 식당의 위도 경도 추가
